### ISSUE TITLE
Allocations overview

### ISSUE THREAD

**Issue by rickomax** [controlflow/resharper-heapview#107]
Can't we have a search function like ReSharper symbol usage search or a "heap allocation overview" which lists all heap allocations inside the file or project?

**Comment by controlflow** [comment]
You can do this with ordinary ReSharper/Rider functionality - "Find similar issues" feature:
![image](https://user-images.githubusercontent.com/194765/210869591-8550eafd-c381-492b-86ab-c3b9f7f877c3.png)

Or you can use "Find code issues" tool window with grouping enabled:
![image](https://user-images.githubusercontent.com/194765/210869801-af4f6adc-c8c3-47e7-b0d8-79a034b4dba8.png)
