### ISSUE TITLE
string.format $"{}" boxing warning in C#10

### ISSUE THREAD

**Issue by HaydenReeve** [controlflow/resharper-heapview#109]
var newFeature = $"Formatting a string with a reference type and a {valueType} in C#10 should not result in a case of boxing."

https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/

**Comment by controlflow** [comment]
Hi. Can you please provide any example of the false positive boxing report?
HeapView is aware of this compiler optimization, no boxing is reported:
![image](https://user-images.githubusercontent.com/194765/228314567-8f738c01-e7ce-4043-9e84-bfb0af0ff587.png)

**Comment by HaydenReeve** [comment]
Hello 👋

My apologies for the delay in getting back to you.

I believe the false positive may in fact be a positive value after all—we're working on a legacy project in the middle of a highly awkward upwards migration and I think that there's some unsupported movement in the framework and c# version control that may be causing this issue.

Thankfully, that makes it my problem and not yours.

Sorry about that—but thank you for your diligent response. Appreciate your hard work!
