### ISSUE TITLE
Is it possible to show a list of allocations across the solution?

### ISSUE THREAD

**Issue by Odaimoko** [controlflow/resharper-heapview#110]
Working on Unity3d with Rider here. We need to minimize heap allocations as much as possible.
It would be great for us if we know the files and method in which the allocations take place.

**Comment by matkoch** [comment]
I assume you mean similar to this: https://github.com/controlflow/resharper-heapview/issues/107#issuecomment-1372674964

Alternatively, you can also launch the action "Run Inspection By Name".
