### ISSUE TITLE
Incorrect boxing allocation warning

### ISSUE THREAD

**Issue by ScrubN** [controlflow/resharper-heapview#119]
In cases where an interpolated string containing a value type is provided as an argument to a method expecting an `object`, the value type is incorrectly flagged as a boxing allocation. 

![image](https://github.com/controlflow/resharper-heapview/assets/72096833/6b49bb55-9cbb-4f97-b66e-6a5aa4021a53)

This can be verified by checking the lowered code (in this case low-level C#), confirming the value type is indeed not boxed by the object cast.
![image](https://github.com/controlflow/resharper-heapview/assets/72096833/38b43751-eb8b-4e75-b623-13a8c6659eea)

**Comment by controlflow** [comment]
Thanks for reporting! This needs fix in ReSharper, interpolated string gets incorrectly classified when being converted to System.Object type. I'll fix this soon and will add more tests to cover this case in the plugin.
