### ISSUE TITLE
"Slow delegate creation" metrics are incorrect.

### ISSUE THREAD

**Issue by hazzik** [controlflow/resharper-heapview#12]
I have a following results:

As you can see _on my machine_ the "slow" delegates have exactly the same results as "normal". 

However there we definetely can see 4 different time patterns: 
1. "Normal" delgates (apprx 00:00:00.014)
2. Delegates from virtual members (apprx 00:00:00.022)
3. Delegates from interface members (apprx 00:00:00.13)
4. Delegates closed with reference types (apprx 00:00:00.4)

My environment: Win 7, x64, .NET 4.5.2, Release, without debugger attached.

The results

1 => 00:00:00.0142181
2 => 00:00:00.0135044
3 => 00:00:00.0134526
4 => 00:00:00.0134764
5 => 00:00:00.0134741
6 => 00:00:00.0131344
7 => 00:00:00.0144817
8 => 00:00:00.0135706
9 => 00:00:00.0142359
10 => 00:00:00.0221315
11 => 00:00:00.0228191
12 => 00:00:00.0223610
13 => 00:00:00.0136163
14 => 00:00:00.0142727
15 => 00:00:00.0221889
16 => 00:00:00.0222276
17 => 00:00:00.1395306 // slow: from interface 'IBar' method
18 => 00:00:00.1352448 // slow: from interface 'IBar' method
19 => 00:00:00.1286564 // slow: from interface 'IBar' method
20 => 00:00:00.1372900 // slow: from interface 'IBar' method
21 => 00:00:00.1368202 // slow: from interface 'IBar' method
22 => 00:00:00.0134871 // slow: anonymous function in a generic method is generic itself (closed with int)
23 => 00:00:00.4364121 // slow: anonymous function in a generic method is generic itself (closed with string)
24 => 00:00:00.0130715 // slow: method group parametrized with type parameter 'T' of method 'GenericTest2' (closed with int)
25 => 00:00:00.4046351 // slow: method group parametrized with type parameter 'T' of method 'GenericTest2' (closed with string)
26 => 00:00:00.0131494 // slow: method group parametrized with type parameter 'T' of method 'GenericTest3' (closed with int)
27 => 00:00:00.4365968 // slow: method group parametrized with type parameter 'T' of method 'GenericTest3' (closed with string)
28 => 00:00:00.0143012
29 => 00:00:00.0159335
30 => 00:00:00.0131130
31 => 00:00:00.3981007
32 => 00:00:00.0132632
33 => 00:00:00.4432385
34 => 00:00:00.0137143
35 => 00:00:00.0157189
36 => 00:00:00.0123428
37 => 00:00:00.0124617
38 => 00:00:00.0123390
39 => 00:00:00.0123479
40 => 00:00:00.0133724
41 => 00:00:00.0134251
42 => 00:00:00.0131928
43 => 00:00:00.4510371
44 => 00:00:00.0144458
45 => 00:00:00.0175602
46 => 00:00:00.0131335
47 => 00:00:00.4492905
48 => 00:00:00.0144066
49 => 00:00:00.0171954
50 => 00:00:00.0119635
51 => 00:00:00.0119602
52 => 00:00:00.0135263
53 => 00:00:00.0133481
54 => 00:00:00.0130999
55 => 00:00:00.3992917
56 => 00:00:00.0131932
57 => 00:00:00.4093388
58 => 00:00:00.0123572
59 => 00:00:00.0123129
60 => 00:00:00.0123526
61 => 00:00:00.3986213
62 => 00:00:00.0131190
63 => 00:00:00.3941653

**Comment by controlflow** [comment]
Obsolete highlighting removed
