### ISSUE TITLE
Visual bug or feature?

### ISSUE THREAD

**Issue by onethousandvoices** [controlflow/resharper-heapview#125]
I just want to know is it normal that orange line is there or not?
![1](https://github.com/controlflow/resharper-heapview/assets/100363602/31308d9b-aa76-47f6-b0d3-0133a8a1a90f)

**Comment by controlflow** [comment]
Well, this is just an unfortunate choice of the highlighting range :) This issue was recently fixed, must be already available in plugin updates for latest Rider 2023.3 EAPs
