### ISSUE TITLE
Turn off the allocations viewer for certain projects

### ISSUE THREAD

**Issue by damageboy** [controlflow/resharper-heapview#21]
Hi,
Normally, I treat these allocations pretty seriously, I stop to think if this is really required etc.

I definitely DO NOT care about this in unit-tests, even more so, specifically in `Assert.That()` statements... Is there a way to control the visualizer's behavior?

**Comment by controlflow** [comment]
You can change severities of HeapView's inspection to "Do not show" mode and save setting to custom project-level settings layer, as [described here](http://blog.jetbrains.com/dotnet/2012/01/18/per-project-settings-or-how-to-have-different-naming-styles-for-my-test-project/).
