### ISSUE TITLE
Bug - Incorrect highlight

### ISSUE THREAD

**Issue by zzz77** [controlflow/resharper-heapview#22]
In screenshot below you can see that there is closure allocation with two parameters but only one parameter is highlighted.

![capture](https://cloud.githubusercontent.com/assets/3635408/8431380/b96848bc-1f41-11e5-937f-1da3af76c736.png)

**Comment by controlflow** [comment]
The idea is to highlight _closure class creation point_, not the captured locals/parameters declarations itself. I was unable to find better place to put highlighting in the case above, closure class actually allocated in the beginning of method execution.

**Comment by zzz77** [comment]
Thanks for explanation!
