### ISSUE TITLE
ReSharper 2016.1 support?

### ISSUE THREAD

**Issue by hmemcpy** [controlflow/resharper-heapview#31]
Pls :)

**Comment by controlflow** [comment]
FML

**Comment by controlflow** [comment]
Let's wait RTM...

**Comment by hmemcpy** [comment]
It's RTM :P

**Comment by controlflow** [comment]
Done

**Comment by hmemcpy** [comment]
:tada: <3

**Comment by VahidN** [comment]
Would you please add ReSharper 2016.2 too? I can't find it in the list of recently updated plugins.

**Comment by controlflow** [comment]
@VahidN it's already available if you enable prerelease plugins view in R# settings. I'm working on release build
