### ISSUE TITLE
string.format highlighting missing in VS2013

### ISSUE THREAD

**Issue by LucaGanio** [controlflow/resharper-heapview#39]
I am using VS2013, R# 2016.3.2 and when I write something like string.Format("{0}", somevalue) the brackets and the reference number are highlighted in green.
But if I install the heap allocation extension this behavior disappears.

**Comment by controlflow** [comment]
Do you have VS2015 also installed on the same machine?
Have you tried to reinstall the HeapView plugin?

I was able to reproduce this behavior once, but can't reproduce it again reliably :/

**Comment by controlflow** [comment]
Seems to be the duplicate of #58
