### ISSUE TITLE
Boxing Allocation (Question)

### ISSUE THREAD

**Issue by Mike-EEE** [controlflow/resharper-heapview#41]
I have another one for you. :)

Consider the following:

![](https://content.screencast.com/users/Mike-EEEE/folders/Jing/media/b7656724-b71d-4727-96e0-660a3c1ad512/2017-03-02_1129.png)

When I switch the call to:

![](https://content.screencast.com/users/Mike-EEEE/folders/Jing/media/812a71e4-4dfe-4415-a673-e948e29f904f/2017-03-02_1129.png)

You can see that the analysis error goes away.  However, the value still ultimate gets boxed once it finds its way into `CheckObject`, correct?  I am looking to verify my understanding here.

**Comment by Mike-EEE** [comment]
Wanted to check in on this.  Is my understanding correct that the value type still gets boxed in the 2nd screenshot?  Or maybe I should open a StackOverflow? 😛

**Comment by controlflow** [comment]
Yes, your understanding is correct, `instance` would box.
Unfortunately, HeapView plugin do not reports possible boxing allocations at this point.

**Comment by Mike-EEE** [comment]
Great, that's basically what I was after, @controlflow.  I was making sure there wasn't some magic I was missing. :) Thank you for your assistance and insight!
