### ISSUE TITLE
Why are C# 7 local functions marked as "Closure allocation"?

### ISSUE THREAD

**Issue by EnCey** [controlflow/resharper-heapview#43]
As per these [C# Design Meeting notes](https://github.com/dotnet/roslyn/issues/3911), the closure for local functions is (or can be) a struct, not a class:

> But with functions, the delegate is never there (unless you explicitly decide to create one when you need it), and if the function itself is not captured as a delegate, **the closure can be a struct on the stack.**

However, all kinds of local functions I tried out were flagged as "Closure allocation".

**Comment by controlflow** [comment]
Thank, I'm aware of this compiler change, but HeapView simply do supports C# 7.0 at this point. Current wrong allocations hints are there only because local functions do implements common interface with lambdas/anonymous methods/query lambdas.
