### ISSUE TITLE
Resharper 2017.2

### ISSUE THREAD

**Issue by kevingosse** [controlflow/resharper-heapview#50]
Hello,

Any plan on supporting new versions of Resharper? I was able to build a custom version for 2017.2 with only minor changes (using the Wave06 project), but I doubt all users will have enough free time for that.

Thanks.

**Comment by FodderMK** [comment]
A vote for 2017.2 as well!

**Comment by kevingosse** [comment]
Oh indeed, I meant 2017.2, my mistake.

In the meantime, I've decided to publish the version I packaged myself: https://resharper-plugins.jetbrains.com/packages/ReSharper.HeapView.R2017.2/
I'll remove it when the original is updated.
