### ISSUE TITLE
ReSharper 2018.1

### ISSUE THREAD

**Issue by RJCo** [controlflow/resharper-heapview#56]
Anyone have a working R# 2018.1 version of this yet?  Only thing keeping me from upgrading R#...can't live without this plugin!

**Comment by ltrzesniewski** [comment]
Well, there's a working version right there: https://github.com/citizenmatt/resharper-heapview/tree/feature/rider but you need to compile and package it yourself. It seems to work well.

@citizenmatt could you push that to the gallery, or are there some things that need to be fixed?

(BTW, the packaging script uses the Debug build, that needs to be changed to Release)

**Comment by friuns2** [comment]
just installed from resharper extensions menu, works fine for me

**Comment by ltrzesniewski** [comment]
@friuns2 yup, this one should have been closed a loooooong time ago.

Also the 2018.2 compatible version got released immediately after the R# release.

**Comment by Mike-EEE** [comment]
How about 2019.1? 😁

**Comment by controlflow** [comment]
Hopefully I'll finish the proper upgrade for 2020.1 soon... with C# 6/7/8 support and .NET Framework/Core JIT optimizations handled... :|
