### ISSUE TITLE
Show allocations due to params modifier

### ISSUE THREAD

**Issue by drewnoakes** [controlflow/resharper-heapview#57]
I don't know all the cases in which calling a method having a `params` parameter results in allocation, but at least some calls must do. I don't see any indication via this extension however.

```c#
void Foo(params object[] bar) { }

Foo(1); // shows boxing
Foo("Foo"); // no indication that object[] is allocated
Foo(); // does this allocate? probably not
```

**Comment by controlflow** [comment]
HeapView had this inspection originally, but it was broken for quite some time :((
Currently it works and handles all the related compiler optimizations (C# compiler uses `System.Array.Empty<T>()` if it's available, when no arguments passed to `params` parameter).
![image](https://user-images.githubusercontent.com/194765/209860893-d0bcc09b-d3f7-47f9-acdf-a65ad05ad3c8.png)
