### ISSUE TITLE
Semantic syntax coloring is messed up

### ISSUE THREAD

**Issue by ltrzesniewski** [controlflow/resharper-heapview#58]
This plugin messes up semantic syntax coloring, that is, this thing:

![image](https://user-images.githubusercontent.com/7913492/44915108-689eae80-ad32-11e8-8271-7a0f24a22925.png)

Here's how some code looks like without the plugin:

![image](https://user-images.githubusercontent.com/7913492/44915136-80763280-ad32-11e8-9294-8be3b1dc666e.png)

Notice the different colors for methods, classes, and structs.

Here's what the same code looks like with the plugin installed:

![image](https://user-images.githubusercontent.com/7913492/44915160-8ff57b80-ad32-11e8-829a-2b80ef01ab34.png)

I'm using VS 15.8.2 with R# 2018.2.1.

IIRC this issue was not present with VS 15.7 and R# 2018.1.

**Comment by nkAlex** [comment]
Yeah, same thing here. I think it has started after one of the recent VS 2017 updates. Only bugs in VS 2017, works fine in 2015 and earlier versions with the same R# installation.

**Comment by Mike-EEE** [comment]
Srsly.

![](https://media.giphy.com/media/XvQXEi09zfmcE/giphy.gif)

**Comment by CheloXL** [comment]
@Mike-EEE Not sure, but I'm quite sure I were the one that helped R# identify this... :) see https://youtrack.jetbrains.com/issue/RSRP-471527

**Comment by Mike-EEE** [comment]
Seriously... I've been suffering for a few weeks now.  I reset my VS settings and everything (never goes well).  It's almost getting to the point of seeking medical attention due to the effects that ass green is having on my mental health.

**Comment by ltrzesniewski** [comment]
@CheloXL maybe you shouldn't encourage them to close the YouTrack ticket, as the problem *may* be caused by R# itself. It would be nice if JetBrains could take a look at it.

**Comment by ltrzesniewski** [comment]
@Mike-EEE BTW if you can't live without the heap allocations viewer, maybe it's time to test Rider 😉 
Yes, it does have this plugin, and no, it doesn't have the coloring issue.

**Comment by Mike-EEE** [comment]
Funny enough I did try doing that, @ltrzesniewski!  Unfortunately, it doesn't support multimon very well at the moment. :(

https://youtrack.jetbrains.com/issue/RIDER-19398
