### ISSUE TITLE
Resharper 2019 support

### ISSUE THREAD

**Issue by maskedmouse** [controlflow/resharper-heapview#61]
Supposedly version 1.2.13 should work with resharper 2019. But the plugin isn't showing up in the list.
[https://plugins.jetbrains.com/plugin/9223-heap-allocations-viewer/versions](url)

Resharper 2019.1.1
Visual Studio Community Edition 2019 v16.0.3

**Comment by shatl** [comment]
Same for me.

**Comment by Mike-EEE** [comment]
Literally the last remaining extension to keep me from upgrading to 2019.1.1.

**Comment by Mike-EEE** [comment]
Nag. :P

https://youtrack.jetbrains.com/issue/RSRP-459966#focus=streamItem-27-3494465.0-0

**Comment by Mike-EEE** [comment]
Apparently, you can download it and install it manually:
https://plugins.jetbrains.com/plugin/12390-heap-allocations-viewer/versions

It would obviously be nice to have it in the Extension Manager, though.

**Comment by maskedmous** [comment]
The question is how?

**Comment by Mike-EEE** [comment]
Durp... apologies.  I THOUGHT EVERYONE KNEW HOW. 😆

I actually didn't know until recently.  You have to add a local path as a source, like you do with nuget.  I am trying it out now to see if it works.

https://www.jetbrains.com/help/resharper/Managing_Extensions.html

**Comment by maskedmous** [comment]
Ah I thought that was only for online repositories not locally downloaded files.. Guess you just have to add the path to the folder right?

**Comment by Mike-EEE** [comment]
Correct... although I am having problems getting it to list there, as well. :(

**Comment by maskedmous** [comment]
Maybe there is the possibility that it is not compatible even though it states it as compatible....

**Comment by CodingGorilla** [comment]
I tried for a while yesterday to get it to work, I tried changing the manifests, changing the nupkg's, all kinds of stuff and could never get R# to load it.

**Comment by Mike-EEE** [comment]
Yeah, that is my guess as well.  Good news is that @matkoch joined in on the thread mentioned earlier and I am thinking he will look into this soon (he mentioned he is the one in charge of this package registration/publishing).

**Comment by matkoch** [comment]
Sorry folks, there was a dependency issue with the recent version. New version  should be available now: https://plugins.jetbrains.com/plugin/12390-heap-allocations-viewer/update/62457

**Comment by maskedmouse** [comment]
Well that works, added it manually as it doesn't show up in the list yet. Works like a charm, thanks!

**Comment by Mike-EEE** [comment]
I can confirm that it does not list:
![](https://i.imgur.com/hFCeckT.png)

Is it queued to be listed in the feed at a later time, perhaps?

**Comment by matkoch** [comment]
Takes a little time for the feed to have changes propagated. Afaik this was brought up internally already. Meanwhile it should show up. At least it does for me :)

**Comment by NimaAra** [comment]
Works fine now, just installed it via the gallery. Thank you.
