### ISSUE TITLE
Boxing is not highlighted

### ISSUE THREAD

**Issue by sebas77** [controlflow/resharper-heapview#63]
Hi,

```c#
public class C {
  public interface INeedEGID {
    int ID { get; set; }
  }
  public struct Test : INeedEGID {
    public int ID { get; set; }
  }
  public void M() {
    var initializer = new Test();
    var needEgid = ((INeedEGID) initializer);
    initializer = (Test) needEgid;
  }
}
```

in this code

```
      var needEgid = ((INeedEGID) initializer);
```

the boxing for the cast of a structure to an interface won't be highlighted in any way.

Version: RD-191.7141.355
Timezone: Europe/London
Evaluation: false
Environment: RD-191.7141.355, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1080x1920, 1920x1080, 1920x1080
Unity: 2019.1.6f1

**Comment by sebas77** [comment]
nobody acknowledges this? Because I have other similar issues and I will report them if you are interested.

**Comment by sebas77** [comment]
[Test]
         public void Test3()
         {
             void Code()
             {
                 void Action()
                 {
                     {
                     }
                 }

                 TestDelegate(Action);
             }
             
             Code();
         }

**Comment by controlflow** [comment]
Both cases should be correct now, thanks for reporting.
![image](https://user-images.githubusercontent.com/194765/209862760-fb3f4353-eb5d-4f2c-bbf3-7b2566c7e28e.png)
![image](https://user-images.githubusercontent.com/194765/209862827-ad77b845-abe5-4d77-beba-ab7fbfdfdd6b.png)
