### ISSUE TITLE
Analyze solution/project?

### ISSUE THREAD

**Issue by znakeeye** [controlflow/resharper-heapview#67]
Would be ultra-nice to be able to analyze a solution or project, to get a nice report of all "unexpected" allocations. E.g. boxing, closures, enumerators...

Maybe it's already there somewhere?

**Comment by matkoch** [comment]
You can alt-enter on an existing inspection, and then choose to find more of them:

![image](https://user-images.githubusercontent.com/5005566/72439706-b42aee80-37a7-11ea-9dda-a01aa90951e4.png)

**Comment by znakeeye** [comment]
Thanks! That does the trick.
