### ISSUE TITLE
Rider 2020.1 Support

### ISSUE THREAD

**Issue by schodemeiss** [controlflow/resharper-heapview#68]
Currently the plugin installs, but I don't see any heap allocations in the editor itself. I've checked through all the settings and I can't see anything different from 2019.3.

**Comment by maksim789456** [comment]
After 2 Rider restarts, the plugin starts working for me.

**Comment by roji** [comment]
See #75, I'm successfully using the plugin with Rider 2020.3.

**Comment by matkoch** [comment]
I assume this is obsolete.
