### ISSUE TITLE
Allocation in nested methods

### ISSUE THREAD

**Issue by eterekhin** [controlflow/resharper-heapview#69]
Hello, look at the screen, please

![image](https://user-images.githubusercontent.com/48148702/76136745-22708c80-6046-11ea-8dea-d62ef69f066b.png)

But, I don't understand why are parameters boxed?
Look at the dotpeek screen:

![image](https://user-images.githubusercontent.com/48148702/76136791-7f6c4280-6046-11ea-92a0-77941903632b.png)

There is no `box` IL instruction
Maybe I don't understand anything, maybe it's a bug

**Comment by controlflow** [comment]
Fixed some time ago, no longer reproduces. Thanks for reporting!
![image](https://user-images.githubusercontent.com/194765/209861435-35c73ccc-45ad-487e-965f-b8b7fbed7061.png)
