### ISSUE TITLE
Show warnings in Errors in solution sidebar

### ISSUE THREAD

**Issue by okproject** [controlflow/resharper-heapview#71]
Hi.

- Is there any chance to see all advices given from heap allocation viewer in somewhere as a list ?

- If not, it is nice idea to show all allocation messages in Error in solutions sidebar

![image](https://user-images.githubusercontent.com/4440992/80852000-ad789800-8c2d-11ea-86a5-3ad88a2ddb38.png)

**Comment by matkoch** [comment]
You can Alt-Enter on an existing highlighting, and then choose to “Find
similar issues in solution”.

Or you invoke “Find issues” directly, and look for the Heap Allocation
group.

**Comment by okproject** [comment]
Wow,
Thank you very much for amazing fast answer.
