### ISSUE TITLE
Ability to enable/disable without restarting

### ISSUE THREAD

**Issue by giuliano-barberi-tf** [controlflow/resharper-heapview#72]
I often would like to enable/disable the heap allocations without restarting the entire IDE. I understand this is currently done at the plugin level hence why the IDE restart is required but I'm wondering if it's possible to add an option for the plugin to show them instead. In most places I might not care about allocations so it's mostly noise, then I get into a part that I need to determine if it's allocating and it requires me to restart the IDE, the workflow would be much better if it was a quick toggle that I could reach from the "Actions" menu instead.

**Comment by roji** [comment]
This would indeed be very helpful - allocations highlighting isn't relevant for all coding, or for all projects. Similarly, the ability to tweak the plugin configuration (don't flag obvious allocations) could be useful.

It would also be useful to be able to configure the plugin on a per-project basis (e.g. in the team or personal settings files). Some projects are very allocation sensitive, while others aren't.

**Comment by controlflow** [comment]
I've added simple options page to temporary disable/enable allocations view:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/194765/195459290-92d96cdc-6ea1-4261-8075-feb24203471f.png">

I'll review other ways to configure the plugin, thanks for reporting this!
