### ISSUE TITLE
Incorrect boxing highlight for string concatenation and modern compilers

### ISSUE THREAD

**Issue by citizenmatt** [controlflow/resharper-heapview#73]
The code `var x = "Hello " + longValue` will show a highlight for boxing of the `longValue` variable. It appears previous compilers would box the value and call `String.Concat(object, object)`. Modern compilers will call `longValue.ToString()` and then call `String.Concat(string, string)`

**Comment by neonb** [comment]
`myPrimitive.ToString()` will still allocate a `string` object, if it hasn't been interned, right? In any case, if modern compilers skip the boxing then the plugin's message at least is incorrect.

**Comment by controlflow** [comment]
Both allocations are now reported:
![image](https://user-images.githubusercontent.com/194765/209862379-b84df08b-4bd6-494d-9829-58245089f8fb.png)
![image](https://user-images.githubusercontent.com/194765/209862463-25c786c6-e31c-4736-9a15-56552f524efe.png)

Boxing is eliminated, but implicit `.ToString()` call still allocates a new string (at least for BCL's numeric types)
