### ISSUE TITLE
Do not show warnings in static data optimization cases

### ISSUE THREAD

**Issue by buybackoff** [controlflow/resharper-heapview#76]
![image](https://user-images.githubusercontent.com/489852/95515037-466dc500-09bd-11eb-90d2-e72087b9c29a.png)

https://github.com/dotnet/roslyn/pull/24621
https://vcsjones.dev/2019/02/01/csharp-readonly-span-bytes-static/

**Comment by lamont-granquist** [comment]
dup of #3?

**Comment by controlflow** [comment]
Fixed
