### ISSUE TITLE
Assigning new array expressions on read-only spans of byte-sized values does not allocate.

### ISSUE THREAD

**Issue by teo-tsirpanis** [controlflow/resharper-heapview#80]
See https://github.com/dotnet/roslyn/pull/24621. The plugin currently displays an allocation on the `new` keyword:

![image](https://user-images.githubusercontent.com/12659251/116861770-57597e80-ac0c-11eb-8df1-1a2e8f2884d0.png)

**Comment by controlflow** [comment]
Note to self: works for byte-sized enums as well
```
using System;
public class C {
    public int M() {
        ReadOnlySpan<E> xs = new E[] { }; // empty span
        ReadOnlySpan<E> ys = new E[] { E.A };
        ReadOnlySpan<E> zs = new E[] { E.A, E.A, E.A };
        return xs.Length + ys.Length + zs.Length;
    }
}

enum E : byte { A }
```

**Comment by controlflow** [comment]
Thanks for reporting! Fix will be available in the next plugin release
