### ISSUE TITLE
Add support for Rider 2021.2 EAP 5.

### ISSUE THREAD

**Issue by AraHaan** [controlflow/resharper-heapview#82]
I would like to use this for those Builds of Rider.

**Comment by matkoch** [comment]
This is currently blocked by https://youtrack.jetbrains.com/issue/RIDER-64653.

We will upload a new version as soon as this is resolved.

**Comment by AraHaan** [comment]
> This is currently blocked by https://youtrack.jetbrains.com/issue/RIDER-64653.
> 
> We will upload a new version as soon as this is resolved.

that issue does not seem to go anywhere.
