### ISSUE TITLE
Wrong parameter closure allocation warning

### ISSUE THREAD

**Issue by DedSec256** [controlflow/resharper-heapview#87]
Repro code: 
```C#
using System.Linq;

class Example
{
  public void A()
  {
    var a = new[] { new[] { 1 } }
      .SelectMany(y => y.Select(x => y[x]))
      .Select(t => t);
  }
}
```

If lambda argument is closed in one of the lambdas in the LINQ chain, subsequent calls in the chain also indicate the allocation of the closure from the lambda argument, which seems suspicious.

![image](https://user-images.githubusercontent.com/26364714/127642169-1e151ce7-7201-44d4-af95-4a30e078043b.png)

**Comment by controlflow** [comment]
Fixed some time ago, no longer reproduces
![image](https://user-images.githubusercontent.com/194765/209861888-85ddc366-e760-4e3e-a0a3-b43856b3221e.png)
