### ISSUE TITLE
Handle target-typed new

### ISSUE THREAD

**Issue by BEagle1984** [controlflow/resharper-heapview#91]
I noticed that the target-typed new initializations aren't properly highlighted.

The `new` keyword in this snippet is properly underlined:
```csharp
ErrorPolicyBuilder builder = new ErrorPolicyBuilder(_endpointsConfigurationBuilder);
```

While this one is not:
```csharp
ErrorPolicyBuilder builder = new(_endpointsConfigurationBuilder);
```

I'm using the latest version (2021.3.0-eap05) on Rider 2021.3 EAP 10, but I don't think it matters.

**Comment by tmenezes** [comment]
Upvote

**Comment by mu88** [comment]
I'd love to see this as well 🤩

**Comment by controlflow** [comment]
Thanks for reporting! Sorry it took so long, it will be fixed in the next release
