### ISSUE TITLE
False positive "Possible boxing allocation" when casting a `class` constrained generic variable

### ISSUE THREAD

**Issue by zenorbi** [controlflow/resharper-heapview#95]
Given the following code, the variable `foo` is definitely a reference type, but I get a warning for
> Possible boxing allocation: type testing 'TFoo' value for 'IDisposable' type possibly requires boxing of value type

```cs
void GenericMethod<TFoo>(TFoo foo) where TFoo : class
{
	if (foo is IDisposable disposable)
	{

	}
}
```

**Comment by controlflow** [comment]
Thanks for reporting! Fixed during boxing analyzer rewrite.
